In [1]:
!pip install transformers

In [2]:
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification

In [3]:
model_name = 'bert-base-uncased'
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name, num_labels=2)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [4]:
# Define the text we want

text = ["This was an amazing product.", "This is the worst thing I have ever bought."]

In [5]:
# Tokenize the text

inputs = tokenizer(text, return_tensors='tf', padding=True, truncation=True, max_length = 30)

In [6]:
# Get the model's prediction

output = model(inputs)
predictions = tf.argmax(output.logits, axis=1)

In [7]:
output

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.4625133 , -0.07601668],
       [-0.5335946 , -0.17007828]], dtype=float32)>, hidden_states=None, attentions=None)

In [8]:
predictions

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [9]:
import numpy as np

np.array(predictions)

array([1, 1])

In [10]:
labels = ['Negative', 'Positive']
for text, prediction in zip(text, predictions):
    print(f"{text}: {labels[prediction]}")

This was an amazing product.: Positive
This is the worst thing I have ever bought.: Positive
